### PR TITLE
Resolves #80 DNS check is problematic in certain environments

### LINKED ISSUE #80: DNS check is problematic in certain environments
The call to `host` in `setup.sh` added 666eb3c2f doesn't work if we're using a hostname that's in `/etc/hosts` but not DNS. I ran into a problem when running in Docker because hostnames are an arbitrary hexidecimal string that get an entry in the `/etc/hosts`, but naturally have no corresponding DNS entry.

I see the following error:
```
[root@0250a97efa16 /]# fluo-dev setup
fluo-dev is using custom configuration at /root/fluo-dev/conf/env.sh
ERROR - Your machine failed to do a DNS lookup of your IP given your hostname using 'host 0250a97efa16'.  This is likely a DNS issue
that can cause fluo-dev services (such as Hadoop) to not start up.  You should confirm that /etc/resolv.conf is correct.
```

Removing the check from `fluo-dev/bin/impl/setup.sh` allows setup to complete seemingly without issue this context. Unfortunately there doesn't seem to be a good way to perform this check that is cross platform. `getent hosts` works on linux, but prefers ipv6 over ipv4, so may return unexpected results.

A stack overflow post suggests something like this that may be most appropriate in this case:

```
hostname=$(hostname)
if [ `grep -c "${hostname}" /etc/hosts` -ge 1 ]; then
   # OK, hostname is in /etc/hosts
elsif [ `host "${hostname}"` -ge 1 ]; then 
   # OK, hostname via DNS
else
   # with message
fi
```

### PR DESCRIPTION
**Pull request by drewfarris**

### CODE REVIEW

File: bin/impl/setup.sh [hunk 1]
```diff
@@ -36,10 +36,15 @@ verify_exist_hash $HADOOP_TARBALL $HADOOP_MD5
...
 verify_exist_hash $SPARK_TARBALL $SPARK_MD5
 
-host `hostname` &> /dev/null
-if [ $? != 0 ]; then
-  echo "ERROR - Your machine failed to do a DNS lookup of your IP given your hostname using 'host `hostname`'.  This is likely a DNS issue"
-  echo "that can cause fluo-dev services (such as Hadoop) to not start up.  You should confirm that /etc/resolv.conf is correct."
+hostname=$(hostname)
+if [ `grep -c "${hostname}" /etc/hosts` -ge 1 ]; then
+  echo "Found ${hostname} in /etc/hosts."
+elif [ `host "${hostname}"` -ge 1 ]; then
```
Comment (mikewalch) [inline bin/impl/setup.sh]: I tested this on my machine and this line was giving my issues.  I think the return code should be checked rather than output of the `host ${hostname}` command.  I modified the script and the following code worked for me:

```bash
hostname=$(hostname)
if [ `grep -c "${hostname}" /etc/hosts` -ge 1 ]; then
  echo "Found ${hostname} in /etc/hosts."
else
  host ${hostname} &> /dev/null
  if [ $? -eq 0 ]; then
    echo "Found ${hostname} in DNS."
  else
    echo "ERROR - Your machine was unable to find its own hostname in /etc/hosts or by using 'host $hostname'."
    echo "This is an issue that can cause fluo-dev services (such as Hadoop) to not start up.  You should"
    echo "confirm that there is an entry in /etc/hosts or that /etc/resolv.conf is correct."
    exit 1
  fi
fi
```

Comment (drewfarris) [inline bin/impl/setup.sh]: Oh, yes of course. Checking the return code makes much more sense., thanks for the update

**Comment by mikewalch** [comment]
I was able to squash and merge the commit using GitHub.  See https://github.com/blog/2141-squash-your-commits
